"""Web-cited jobs versus SZL organs. Search our catalog, not a live scrape.

We searched the leaders, encoded the job, and refuse to rehost the code.
Signing stays UNSIGNED-honest (tamper-evident, not Sigstore/Cosign).
Energy stays UNAVAILABLE. Λ stays Conjecture 1.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass

from .cells import FRONTIERS, LYTE, Cell

# Typo / shorthand → canonical needle. Search is catalog, not a live crawl.
ALIASES: dict[str, str] = {
    "vlm": "vllm",
    "v-llm": "vllm",
    "vlmm": "vllm",
    "sgl": "sglang",
    "langraph": "langgraph",
    "lang graph": "langgraph",
    "llama-guard": "llama guard",
    "llamaguard": "llama guard",
    "retrive": "retrieve",
    "retriev": "retrieve",
    "rag": "llamaindex",
    "llama-index": "llamaindex",
    "llama index": "llamaindex",
    "memgpt": "letta",
    "obsv": "observe",
    "observ": "observe",
    "observability": "phoenix",
    "otel": "phoenix",
    "opentelemetry": "phoenix",
    "qlora": "unsloth",
    "lora": "unsloth",
    "finetune": "unsloth",
    "fine-tune": "unsloth",
    "json-mode": "outlines",
    "jsonmode": "outlines",
    "structured": "outlines",
    "pydantic": "instructor",
    "trt": "tensorrt",
    "tensorrt-llm": "tensorrt",
    "n9": "retrieve",
    "n10": "observe",
    "n11": "tune",
    "n12": "schema",
    "n13": "energy",
    "n14": "mcp",
    "n15": "mem0",
    "n16": "ragas",
    "n17": "dynamo",
    "n18": "litellm",
    "n19": "lmcache",
    "n20": "livekit",
    "n21": "daytona",
    "n22": "spiffe",
    "n23": "nemo",
    "n24": "playwright",
    "n25": "cedar",
    "mcp": "mcp",
    "mem0": "mem0",
    "zep": "zep",
    "graphiti": "zep",
    "ragas": "ragas",
    "helm": "helm",
    "arena": "arena",
    "dynamo": "dynamo",
    "rayserve": "ray",
    "llm-d": "llm-d",
    "llmd": "llm-d",
    "litellm": "litellm",
    "openrouter": "openrouter",
    "routellm": "routellm",
    "gateway": "litellm",
    "lmcache": "lmcache",
    "mooncake": "mooncake",
    "gptcache": "gptcache",
    "livekit": "livekit",
    "cartesia": "cartesia",
    "deepgram": "deepgram",
    "daytona": "daytona",
    "e2b": "e2b",
    "spiffe": "spiffe",
    "spire": "spire",
    "astrix": "astrix",
    "nhi": "astrix",
    "nemo": "nemo",
    "colang": "nemo",
    "rails": "nemo",
    "playwright": "playwright",
    "stagehand": "stagehand",
    "browserbase": "browserbase",
    "skyvern": "skyvern",
    "cedar": "cedar",
    "opa": "opa",
    "rego": "opa",
}


@dataclass(frozen=True)
class Job:
    id: str
    title: str
    leader: str
    url: str
    organ: str
    cell: str
    honesty: str
    admitted: bool
    take: str
    refuse: str


JOBS: tuple[Job, ...] = (
    Job(
        id="lyte",
        title="Lyte design-partner cell",
        leader="SZL owner order",
        url="https://github.com/szl-holdings/a11oy-factory",
        organ="heart",
        cell="lyte",
        honesty="STRUCTURAL-ONLY",
        admitted=True,
        take="BIND_AS_A11OY_PACKAGE. Schema-checked bind into a11oy.",
        refuse="Not a second flagship. Formulas never grant authority.",
    ),
    Job(
        id="vllm",
        title="Production LLM serving",
        leader="vLLM",
        url="https://github.com/vllm-project/vllm",
        organ="brain",
        cell="N1",
        honesty="LIVE",
        admitted=False,
        take="Receipted fail-closed serving. Schema outside the weights. OpenAI-shaped /v1.",
        refuse="Do not rehost vLLM, PagedAttention, or their kernels.",
    ),
    Job(
        id="sglang",
        title="Agentic / structured serving",
        leader="SGLang",
        url="https://github.com/sgl-project/sglang",
        organ="brain",
        cell="N1",
        honesty="LIVE",
        admitted=False,
        take="Prefix-reuse and structured output as a serving job, under receipts.",
        refuse="Do not rehost RadixAttention or SGLang runtime.",
    ),
    Job(
        id="ollama",
        title="Local developer serving",
        leader="Ollama",
        url="https://github.com/ollama/ollama",
        organ="brain",
        cell="N1",
        honesty="LIVE",
        admitted=False,
        take="Honest local DX path wrapping llama.cpp. CPU-honest until GPU is MEASURED.",
        refuse="Do not rehost Ollama. Do not claim GPU serve LIVE.",
    ),
    Job(
        id="tensorrt",
        title="Hardware-optimized serving",
        leader="TensorRT-LLM",
        url="https://github.com/NVIDIA/TensorRT-LLM",
        organ="brain",
        cell="N1",
        honesty="LIVE",
        admitted=False,
        take="Receipted serve on measured NVIDIA hardware. Energy stays UNAVAILABLE until NVML.",
        refuse="Do not rehost TensorRT-LLM. Do not fabricate GPU LIVE.",
    ),
    Job(
        id="langgraph",
        title="Stateful agent graph",
        leader="LangGraph",
        url="https://www.langchain.com/langgraph",
        organ="nervous",
        cell="N2",
        honesty="LIVE",
        admitted=False,
        take="Durable graph, checkpoint, human-in-the-loop. SENTRA on every edge.",
        refuse="Do not rehost LangGraph StateGraph or interrupt().",
    ),
    Job(
        id="llamaguard",
        title="Prompt and response safeguard",
        leader="Llama Guard",
        url="https://ai.meta.com/research/publications/llama-guard-llm-based-input-output-safeguard-for-human-ai-conversations/",
        organ="immune",
        cell="N3",
        honesty="LIVE",
        admitted=False,
        take="Classify prompt and response. Fail closed on taxonomy hits.",
        refuse="Do not rehost Llama Guard weights or Purple Llama.",
    ),
    Job(
        id="mosaic",
        title="Own-data mosaic",
        leader="MosaicML / Databricks Mosaic AI",
        url="https://www.databricks.com/blog/databricks-mosaicml",
        organ="circulatory",
        cell="N4",
        honesty="LIVE",
        admitted=False,
        take="Receipted mosaic with UNSIGNED-honest lineage on own data.",
        refuse="Do not rehost MosaicML, Mosaic AI, or the lakehouse.",
    ),
    Job(
        id="lattice",
        title="Defense overlay",
        leader="immune-lattice",
        url="https://github.com/szl-holdings/immune-lattice",
        organ="immune",
        cell="N5",
        honesty="LIVE",
        admitted=False,
        take="SENTRA/YAWAR overlay on every cell. Defense only.",
        refuse="Hub vertical may be LIVE. This frontier bind is not. Never strike people.",
    ),
    Job(
        id="guidewire",
        title="P&C insurance core",
        leader="Guidewire",
        url="https://www.guidewire.com/",
        organ="heart",
        cell="N6",
        honesty="LIVE",
        admitted=False,
        take="Allodial/counsel bind for policy, billing, claims jobs.",
        refuse="Do not rehost Guidewire InsuranceSuite. Formulas never grant authority.",
    ),
    Job(
        id="quantconnect",
        title="Algorithmic research and backtest",
        leader="QuantConnect LEAN",
        url="https://www.quantconnect.com/",
        organ="brain",
        cell="N7",
        honesty="LIVE",
        admitted=False,
        take="Receipted backtest. Actuation SIMULATED.",
        refuse="Not a broker. Do not rehost LEAN. A price is not a fill.",
    ),
    Job(
        id="zillow",
        title="Property records",
        leader="Zillow",
        url="https://www.zillow.com/",
        organ="skeleton",
        cell="N8",
        honesty="LIVE",
        admitted=False,
        take="Receipted title/underwrite bind on public records.",
        refuse="Do not rehost Zillow. szl-real-estate Hub vertical may be LIVE; this bind is not.",
    ),
    Job(
        id="llamaindex",
        title="Retrieval-augmented generation",
        leader="LlamaIndex",
        url="https://github.com/run-llama/llama_index",
        organ="nervous",
        cell="N9",
        honesty="LIVE",
        admitted=False,
        take="Receipted retrieve. SENTRA on every chunk. Schema outside the weights.",
        refuse="Do not rehost LlamaIndex, its indices, or its query engines.",
    ),
    Job(
        id="haystack",
        title="Production retrieval pipelines",
        leader="Haystack",
        url="https://github.com/deepset-ai/haystack",
        organ="nervous",
        cell="N9",
        honesty="LIVE",
        admitted=False,
        take="Pipeline job under receipts. Fail closed on empty evidence.",
        refuse="Do not rehost Haystack pipelines.",
    ),
    Job(
        id="letta",
        title="Persistent agent memory",
        leader="Letta / MemGPT",
        url="https://github.com/letta-ai/letta",
        organ="nervous",
        cell="N9",
        honesty="LIVE",
        admitted=False,
        take="Memory as a receipted organ. Not a second brain without SENTRA.",
        refuse="Do not rehost Letta or MemGPT.",
    ),
    Job(
        id="phoenix",
        title="OpenTelemetry LLM traces and evals",
        leader="Arize Phoenix",
        url="https://github.com/Arize-ai/phoenix",
        organ="immune",
        cell="N10",
        honesty="LIVE",
        admitted=False,
        take="YAWAR receipt traces. Honest UNAVAILABLE over fabricated green.",
        refuse="Do not rehost Phoenix. Phoenix is ELv2, not Apache-2.0.",
    ),
    Job(
        id="langsmith",
        title="LangChain agent traces",
        leader="LangSmith",
        url="https://www.langchain.com/langsmith",
        organ="immune",
        cell="N10",
        honesty="LIVE",
        admitted=False,
        take="Trace every SENTRA edge. Receipt the cycle.",
        refuse="Do not rehost LangSmith.",
    ),
    Job(
        id="langfuse",
        title="OSS LLM traces",
        leader="Langfuse",
        url="https://github.com/langfuse/langfuse",
        organ="immune",
        cell="N10",
        honesty="LIVE",
        admitted=False,
        take="Self-hostable traces as YAWAR packets.",
        refuse="Do not rehost Langfuse.",
    ),
    Job(
        id="deepeval",
        title="CI evaluation",
        leader="DeepEval",
        url="https://github.com/confident-ai/deepeval",
        organ="immune",
        cell="N10",
        honesty="LIVE",
        admitted=False,
        take="Eval in CI with UNSIGNED-honest receipts. Never grade our own homework LIVE.",
        refuse="Do not rehost DeepEval or claim eval LIVE.",
    ),
    Job(
        id="unsloth",
        title="Receipted QLoRA",
        leader="Unsloth",
        url="https://github.com/unslothai/unsloth",
        organ="brain",
        cell="N11",
        honesty="LIVE",
        admitted=False,
        take="Fine-tunes only against LIVE weights with a receipt. GPU ROADMAP.",
        refuse="No unreceipted QLoRA. Not an Unsloth rehost.",
    ),
    Job(
        id="outlines",
        title="Constrained decode",
        leader="Outlines",
        url="https://github.com/dottxt-ai/outlines",
        organ="skeleton",
        cell="N12",
        honesty="LIVE",
        admitted=False,
        take="Finite-state schema outside the weights.",
        refuse="Do not rehost Outlines or its FSMs.",
    ),
    Job(
        id="instructor",
        title="Pydantic structured outputs",
        leader="Instructor",
        url="https://github.com/instructor-ai/instructor",
        organ="skeleton",
        cell="N12",
        honesty="LIVE",
        admitted=False,
        take="Typed receipts. Schema stays outside the weights.",
        refuse="Do not rehost Instructor.",
    ),
    Job(
        id="sigstore",
        title="Keyless artifact signing",
        leader="Sigstore / Cosign",
        url="https://www.sigstore.dev/",
        organ="skeleton",
        cell="",
        honesty="STRUCTURAL-ONLY",
        admitted=False,
        take="UNSIGNED-honest SHA-256 is tamper-EVIDENT.",
        refuse="Not a signature. Not Cosign. Not Fulcio. Signing stays STRUCTURAL-ONLY.",
    ),
    Job(
        id="energy",
        title="Measured joule channel",
        leader="Intel RAPL / NVIDIA NVML",
        url="https://github.com/szl-holdings/governed-inference-meter",
        organ="nervous",
        cell="N13",
        honesty="UNAVAILABLE",
        admitted=False,
        take="Joule MEASURED only from RAPL or NVML. Energy channel may be LIVE; the joule is not.",
        refuse="Do not fabricate joules. Do not clone Electricity Maps.",
    ),
    Job(
        id="maps",
        title="Grid carbon accounting",
        leader="Electricity Maps",
        url="https://www.electricitymaps.com/",
        organ="circulatory",
        cell="N13",
        honesty="UNAVAILABLE",
        admitted=False,
        take="Carbon intensity stays UNAVAILABLE until a MEASURED feed exists.",
        refuse="Do not clone Electricity Maps. Do not mint a green joule.",
    ),
    Job(
        id="wrap",
        title="Wrapped inference joule",
        leader="szl-command-lab NVML wrap",
        url="https://github.com/szl-holdings/szl-command-lab",
        organ="nervous",
        cell="N26",
        honesty="REPORTED",
        admitted=False,
        take="Board energy during a wrapped SHA-256 kernel on command-lab. REPORTED here. MEASURED there.",
        refuse="Do not fabricate joules. Do not claim MEASURED on this CPU factory. Do not elevate proven_trust.",
    ),
    Job(
        id="mcp",
        title="Agent tool protocol",
        leader="Anthropic MCP",
        url="https://modelcontextprotocol.io",
        organ="nervous",
        cell="N14",
        honesty="LIVE",
        admitted=False,
        take="SENTRA-gated tools. Fail closed on unknown tools.",
        refuse="Do not rehost MCP servers, SDKs, or the 2026-07-28 spec.",
    ),
    Job(
        id="mem0",
        title="Extract-and-retrieve memory",
        leader="Mem0",
        url="https://github.com/mem0ai/mem0",
        organ="brain",
        cell="N15",
        honesty="LIVE",
        admitted=False,
        take="Receipted memory. YAWAR lineage on every write.",
        refuse="Do not rehost Mem0 extract pipelines.",
    ),
    Job(
        id="zep",
        title="Temporal knowledge-graph memory",
        leader="Zep Graphiti",
        url="https://github.com/getzep/graphiti",
        organ="brain",
        cell="N15",
        honesty="LIVE",
        admitted=False,
        take="Temporal facts under receipts. Not a live graph clone.",
        refuse="Do not rehost Graphiti or Zep.",
    ),
    Job(
        id="ragas",
        title="RAG evaluation metrics",
        leader="RAGAS",
        url="https://github.com/explodinggradients/ragas",
        organ="immune",
        cell="N16",
        honesty="LIVE",
        admitted=False,
        take="Receipted faithfulness/precision/recall. No self-grading as LIVE.",
        refuse="Do not rehost RAGAS.",
    ),
    Job(
        id="helm",
        title="Holistic evaluation",
        leader="Stanford HELM",
        url="https://crfm.stanford.edu/helm/",
        organ="immune",
        cell="N16",
        honesty="LIVE",
        admitted=False,
        take="Receipted holistic eval. Conjecture 1 stays OPEN.",
        refuse="Do not rehost HELM.",
    ),
    Job(
        id="arena",
        title="Pairwise live evaluation",
        leader="LMSYS Chatbot Arena",
        url="https://lmarena.ai",
        organ="immune",
        cell="N16",
        honesty="LIVE",
        admitted=False,
        take="Pairwise votes as a job. Not a leaderboard rehost.",
        refuse="Do not rehost Chatbot Arena or lmarena.ai.",
    ),
    Job(
        id="dynamo",
        title="Disaggregated distributed serving",
        leader="NVIDIA Dynamo",
        url="https://github.com/ai-dynamo/dynamo",
        organ="circulatory",
        cell="N17",
        honesty="LIVE",
        admitted=False,
        take="Receipted overlay above engines. Not the engine.",
        refuse="Do not rehost Dynamo, disaggregated prefill/decode, or KV routing.",
    ),
    Job(
        id="ray",
        title="Distributed Serve LLM",
        leader="Ray Serve LLM",
        url="https://docs.ray.io/en/latest/serve/llm/index.html",
        organ="circulatory",
        cell="N17",
        honesty="LIVE",
        admitted=False,
        take="Distributed batch and serve as a job under receipts.",
        refuse="Do not rehost Ray or Ray Serve.",
    ),
    Job(
        id="llmd",
        title="Kubernetes-native distributed inference",
        leader="llm-d",
        url="https://github.com/llm-d/llm-d",
        organ="circulatory",
        cell="N17",
        honesty="LIVE",
        admitted=False,
        take="K8s-native overlay. GPU ROADMAP.",
        refuse="Do not rehost llm-d.",
    ),
    Job(
        id="litellm",
        title="Open-source LLM gateway",
        leader="LiteLLM",
        url="https://github.com/BerriAI/litellm",
        organ="circulatory",
        cell="N18",
        honesty="LIVE",
        admitted=False,
        take="Receipted OpenAI-format gateway. Fail closed on unknown providers. Spend is a receipt.",
        refuse="Do not rehost LiteLLM proxy, virtual keys, or the 100+ provider map.",
    ),
    Job(
        id="openrouter",
        title="Hosted model marketplace",
        leader="OpenRouter",
        url="https://openrouter.ai/",
        organ="circulatory",
        cell="N18",
        honesty="LIVE",
        admitted=False,
        take="Aggregator as a job. Not an account at every provider.",
        refuse="Do not rehost OpenRouter. A marketplace is not a mesh.",
    ),
    Job(
        id="routellm",
        title="Learned request routing",
        leader="RouteLLM",
        url="https://github.com/lm-sys/RouteLLM",
        organ="circulatory",
        cell="N18",
        honesty="LIVE",
        admitted=False,
        take="The routing decision itself, under receipts. Distinct from the gateway.",
        refuse="Do not rehost RouteLLM. Do not pretend a learned router is LIVE.",
    ),
    Job(
        id="lmcache",
        title="KV cache offload",
        leader="LMCache",
        url="https://github.com/LMCache/LMCache",
        organ="circulatory",
        cell="N19",
        honesty="LIVE",
        admitted=False,
        take="Receipted prefix reuse next to N1 serve. A hit is not a new thought.",
        refuse="Do not rehost LMCache. Do not claim GPU cache LIVE.",
    ),
    Job(
        id="mooncake",
        title="KV transfer plane",
        leader="Mooncake",
        url="https://github.com/kvcache-ai/Mooncake",
        organ="circulatory",
        cell="N19",
        honesty="LIVE",
        admitted=False,
        take="KV movement as a job under receipts.",
        refuse="Do not rehost Mooncake.",
    ),
    Job(
        id="gptcache",
        title="Semantic response cache",
        leader="GPTCache",
        url="https://github.com/zilliztech/GPTCache",
        organ="circulatory",
        cell="N19",
        honesty="LIVE",
        admitted=False,
        take="Semantic reuse with YAWAR lineage. Stale is fail-closed.",
        refuse="Do not rehost GPTCache.",
    ),
    Job(
        id="livekit",
        title="Realtime agent rooms",
        leader="LiveKit Agents",
        url="https://github.com/livekit/agents",
        organ="nervous",
        cell="N20",
        honesty="LIVE",
        admitted=False,
        take="Receipted duplex rooms. Audio is not authority.",
        refuse="Do not rehost LiveKit Agents or the SFU.",
    ),
    Job(
        id="cartesia",
        title="Low-latency speech synthesis",
        leader="Cartesia",
        url="https://cartesia.ai/",
        organ="nervous",
        cell="N20",
        honesty="LIVE",
        admitted=False,
        take="TTS as a job. Voice is not a person.",
        refuse="Do not rehost Cartesia.",
    ),
    Job(
        id="deepgram",
        title="Streaming speech recognition",
        leader="Deepgram",
        url="https://deepgram.com/",
        organ="nervous",
        cell="N20",
        honesty="LIVE",
        admitted=False,
        take="STT as a job. Transcripts get receipts.",
        refuse="Do not rehost Deepgram.",
    ),
    Job(
        id="daytona",
        title="Agent-native sandboxed workspaces",
        leader="Daytona",
        url="https://github.com/daytonaio/daytona",
        organ="skeleton",
        cell="N21",
        honesty="LIVE",
        admitted=False,
        take="SENTRA-gated exec. Escape is fail-closed.",
        refuse="Do not rehost Daytona.",
    ),
    Job(
        id="e2b",
        title="MicroVM code interpreter",
        leader="E2B",
        url="https://github.com/e2b-dev/E2B",
        organ="skeleton",
        cell="N21",
        honesty="LIVE",
        admitted=False,
        take="Firecracker isolation as a job. Not a second kernel.",
        refuse="Do not rehost E2B.",
    ),
    Job(
        id="spiffe",
        title="Workload non-human identity",
        leader="SPIFFE / SPIRE",
        url="https://spiffe.io/",
        organ="skeleton",
        cell="N22",
        honesty="LIVE",
        admitted=False,
        take="UNSIGNED-honest spiffe-shaped id. Tamper-evident, not an SVID.",
        refuse="Do not rehost SPIRE. Not a certificate. Not Cosign.",
    ),
    Job(
        id="astrix",
        title="Agent NHI discovery and policy",
        leader="Astrix",
        url="https://astrix.security/",
        organ="skeleton",
        cell="N22",
        honesty="LIVE",
        admitted=False,
        take="Inventory NHIs under receipts. Policy fail closed.",
        refuse="Do not rehost Astrix.",
    ),
    Job(
        id="nemo",
        title="Programmable conversation rails",
        leader="NVIDIA NeMo Guardrails",
        url="https://github.com/NVIDIA-NeMo/Guardrails",
        organ="immune",
        cell="N23",
        honesty="LIVE",
        admitted=False,
        take="Topic rails. Off-rail HALT. Distinct from Llama Guard on N3.",
        refuse="Do not rehost NeMo Guardrails or Colang.",
    ),
    Job(
        id="playwright",
        title="Browser control loop",
        leader="Playwright",
        url="https://github.com/microsoft/playwright",
        organ="nervous",
        cell="N24",
        honesty="LIVE",
        admitted=False,
        take="No actuation. Navigation refused.",
        refuse="Do not rehost Playwright.",
    ),
    Job(
        id="stagehand",
        title="Act / extract / observe on Chromium",
        leader="Stagehand",
        url="https://github.com/browserbase/stagehand",
        organ="nervous",
        cell="N24",
        honesty="LIVE",
        admitted=False,
        take="Browser primitives as a job. Not a live agent.",
        refuse="Do not rehost Stagehand.",
    ),
    Job(
        id="browserbase",
        title="Managed agent Chromium",
        leader="Browserbase",
        url="https://www.browserbase.com/",
        organ="nervous",
        cell="N24",
        honesty="LIVE",
        admitted=False,
        take="Managed browser as a job. No navigation LIVE.",
        refuse="Do not rehost Browserbase.",
    ),
    Job(
        id="skyvern",
        title="Vision-first browser workflows",
        leader="Skyvern",
        url="https://github.com/Skyvern-AI/skyvern",
        organ="nervous",
        cell="N24",
        honesty="LIVE",
        admitted=False,
        take="Workflow job under receipts. AGPL is a refuse, not a clone.",
        refuse="Do not rehost Skyvern.",
    ),
    Job(
        id="cedar",
        title="Policy-as-code authorization",
        leader="AWS Cedar",
        url="https://www.cedarpolicy.com/",
        organ="immune",
        cell="N25",
        honesty="LIVE",
        admitted=False,
        take="SENTRA policy. Unknown action fail closed.",
        refuse="Do not rehost Cedar.",
    ),
    Job(
        id="opa",
        title="General policy engine",
        leader="Open Policy Agent",
        url="https://www.openpolicyagent.org/",
        organ="immune",
        cell="N25",
        honesty="LIVE",
        admitted=False,
        take="Rego-shaped refuse. Not a sidecar mesh clone.",
        refuse="Do not rehost OPA or Rego.",
    ),
)


def _blob(job: Job) -> str:
    return " ".join(
        [
            job.id,
            job.title,
            job.leader,
            job.organ,
            job.cell,
            job.honesty,
            job.take,
            job.refuse,
        ]
    ).lower()


def _cell_blob(cell: Cell) -> str:
    return " ".join(
        [cell.id, cell.title, cell.job, cell.cite, cell.szl, cell.note, cell.organ]
    ).lower()


def _needles(q: str) -> list[str]:
    raw = (q or "").strip().lower()
    if not raw:
        return []
    expanded = ALIASES.get(raw, raw)
    out: list[str] = []
    for n in (raw, expanded):
        if n and n not in out:
            out.append(n)
    # Only tokenize an alias expansion (vlm → vllm stays one token).
    # Never split "llama guard" into "llama"+"guard" — that hits Ollama.
    if " " not in raw and " " in expanded:
        for t in expanded.split():
            if t and t not in out:
                out.append(t)
    return out


def search_jobs(q: str) -> dict:
    """Local catalog search. Empty query returns the full table. Unknown query is empty hits, not an error."""
    needles = _needles(q)
    jobs = [asdict(j) for j in JOBS if not needles or any(n in _blob(j) for n in needles)]
    cells = [
        c.__dict__
        for c in (LYTE, *FRONTIERS)
        if not needles or any(n in _cell_blob(c) for n in needles)
    ]
    return {
        "query": q or "",
        "jobs": jobs,
        "cells": cells,
        "lambda_status": "Conjecture 1",
        "energy": None,
        "signer": "UNSIGNED-honest",
        "note": "Catalog of cited jobs. Not a live web crawl. We take the job, not the code.",
    }
