/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellAdmissionRouteImport } from './routes/_shell/admission'
import { Route as ShellCompanyRouteImport } from './routes/_shell/company'
import { Route as ShellConsoleRouteImport } from './routes/_shell/console'
import { Route as ShellEstateRouteImport } from './routes/_shell/estate'
import { Route as ShellEvidenceRouteImport } from './routes/_shell/evidence'
import { Route as ShellFrontierRouteImport } from './routes/_shell/frontier'
import { Route as ShellInvestorRouteImport } from './routes/_shell/investor'
import { Route as ShellKillinchuRouteImport } from './routes/_shell/killinchu'
import { Route as ShellResearchRouteImport } from './routes/_shell/research'
import { Route as ShellSpacesRouteImport } from './routes/_shell/spaces'
import { Route as ShellTrustRouteImport } from './routes/_shell/trust'
import { Route as ShellVerifyRouteImport } from './routes/_shell/verify'
import { Route as ShellConsoleObservabilityRouteImport } from './routes/_shell/console.observability'
import { Route as ShellVerticalsIdRouteImport } from './routes/_shell/verticals.$id'
import { Route as ApiA11oyTabMatrixRouteImport } from './routes/api/a11oy/tab-matrix'
import { Route as ApiA11oyV1AdmissionRouteImport } from './routes/api/a11oy/v1/admission'
import { Route as ApiA11oyV1FrontierRouteImport } from './routes/api/a11oy/v1/frontier'
import { Route as ApiA11oyV1GenomeRouteImport } from './routes/api/a11oy/v1/genome'
import { Route as ApiA11oyV1HonestRouteImport } from './routes/api/a11oy/v1/honest'
import { Route as ApiA11oyV1LedgerRouteImport } from './routes/api/a11oy/v1/ledger'
import { Route as ApiA11oyV1OrgansRouteImport } from './routes/api/a11oy/v1/organs'
import { Route as ApiA11oyV1OrgansHistoryRouteImport } from './routes/api/a11oy/v1/organs.history'
import { Route as ApiA11oyV1OrgansIdRouteImport } from './routes/api/a11oy/v1/organs.$id'
import { Route as ApiA11oyV1SpacesRouteImport } from './routes/api/a11oy/v1/spaces'
import { Route as ApiA11oyV1SpacesHealthRouteImport } from './routes/api/a11oy/v1/spaces/health'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdmissionRoute = ShellAdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCompanyRoute = ShellCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConsoleRoute = ShellConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEstateRoute = ShellEstateRouteImport.update({
  id: '/estate',
  path: '/estate',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEvidenceRoute = ShellEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFrontierRoute = ShellFrontierRouteImport.update({
  id: '/frontier',
  path: '/frontier',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInvestorRoute = ShellInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => ShellRoute,
} as any)
const ShellKillinchuRoute = ShellKillinchuRouteImport.update({
  id: '/killinchu',
  path: '/killinchu',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResearchRoute = ShellResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSpacesRoute = ShellSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTrustRoute = ShellTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVerifyRoute = ShellVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConsoleObservabilityRoute =
  ShellConsoleObservabilityRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => ShellConsoleRoute,
  } as any)
const ShellVerticalsIdRoute = ShellVerticalsIdRouteImport.update({
  id: '/verticals/$id',
  path: '/verticals/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ApiA11oyTabMatrixRoute = ApiA11oyTabMatrixRouteImport.update({
  id: '/api/a11oy/tab-matrix',
  path: '/api/a11oy/tab-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiA11oyV1AdmissionRoute = ApiA11oyV1AdmissionRouteImport.update({
  id: '/api/a11oy/v1/admission',
  path: '/api/a11oy/v1/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiA11oyV1FrontierRoute = ApiA11oyV1FrontierRouteImport.update({
  id: '/api/a11oy/v1/frontier',
  path: '/api/a11oy/v1/frontier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiA11oyV1GenomeRoute = ApiA11oyV1GenomeRouteImport.update({
  id: '/api/a11oy/v1/genome',
  path: '/api/a11oy/v1/genome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiA11oyV1HonestRoute = ApiA11oyV1HonestRouteImport.update({
  id: '/api/a11oy/v1/honest',
  path: '/api/a11oy/v1/honest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiA11oyV1LedgerRoute = ApiA11oyV1LedgerRouteImport.update({
  id: '/api/a11oy/v1/ledger',
  path: '/api/a11oy/v1/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiA11oyV1OrgansRoute = ApiA11oyV1OrgansRouteImport.update({
  id: '/api/a11oy/v1/organs',
  path: '/api/a11oy/v1/organs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiA11oyV1OrgansHistoryRoute = ApiA11oyV1OrgansHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ApiA11oyV1OrgansRoute,
} as any)
const ApiA11oyV1OrgansIdRoute = ApiA11oyV1OrgansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiA11oyV1OrgansRoute,
} as any)
const ApiA11oyV1SpacesRoute = ApiA11oyV1SpacesRouteImport.update({
  id: '/api/a11oy/v1/spaces',
  path: '/api/a11oy/v1/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiA11oyV1SpacesHealthRoute = ApiA11oyV1SpacesHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ApiA11oyV1SpacesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/healthz': typeof HealthzRoute
  '/readyz': typeof ReadyzRoute
  '/admission': typeof ShellAdmissionRoute
  '/company': typeof ShellCompanyRoute
  '/console': typeof ShellConsoleRouteWithChildren
  '/estate': typeof ShellEstateRoute
  '/evidence': typeof ShellEvidenceRoute
  '/frontier': typeof ShellFrontierRoute
  '/investor': typeof ShellInvestorRoute
  '/killinchu': typeof ShellKillinchuRoute
  '/research': typeof ShellResearchRoute
  '/spaces': typeof ShellSpacesRoute
  '/trust': typeof ShellTrustRoute
  '/verify': typeof ShellVerifyRoute
  '/console/observability': typeof ShellConsoleObservabilityRoute
  '/verticals/$id': typeof ShellVerticalsIdRoute
  '/api/a11oy/tab-matrix': typeof ApiA11oyTabMatrixRoute
  '/api/a11oy/v1/admission': typeof ApiA11oyV1AdmissionRoute
  '/api/a11oy/v1/frontier': typeof ApiA11oyV1FrontierRoute
  '/api/a11oy/v1/genome': typeof ApiA11oyV1GenomeRoute
  '/api/a11oy/v1/honest': typeof ApiA11oyV1HonestRoute
  '/api/a11oy/v1/ledger': typeof ApiA11oyV1LedgerRoute
  '/api/a11oy/v1/organs': typeof ApiA11oyV1OrgansRouteWithChildren
  '/api/a11oy/v1/organs/history': typeof ApiA11oyV1OrgansHistoryRoute
  '/api/a11oy/v1/organs/$id': typeof ApiA11oyV1OrgansIdRoute
  '/api/a11oy/v1/spaces': typeof ApiA11oyV1SpacesRouteWithChildren
  '/api/a11oy/v1/spaces/health': typeof ApiA11oyV1SpacesHealthRoute
}
export interface FileRoutesByTo {
  '/healthz': typeof HealthzRoute
  '/readyz': typeof ReadyzRoute
  '/admission': typeof ShellAdmissionRoute
  '/company': typeof ShellCompanyRoute
  '/console': typeof ShellConsoleRouteWithChildren
  '/estate': typeof ShellEstateRoute
  '/evidence': typeof ShellEvidenceRoute
  '/frontier': typeof ShellFrontierRoute
  '/investor': typeof ShellInvestorRoute
  '/killinchu': typeof ShellKillinchuRoute
  '/research': typeof ShellResearchRoute
  '/spaces': typeof ShellSpacesRoute
  '/trust': typeof ShellTrustRoute
  '/verify': typeof ShellVerifyRoute
  '/': typeof ShellIndexRoute
  '/console/observability': typeof ShellConsoleObservabilityRoute
  '/verticals/$id': typeof ShellVerticalsIdRoute
  '/api/a11oy/tab-matrix': typeof ApiA11oyTabMatrixRoute
  '/api/a11oy/v1/admission': typeof ApiA11oyV1AdmissionRoute
  '/api/a11oy/v1/frontier': typeof ApiA11oyV1FrontierRoute
  '/api/a11oy/v1/genome': typeof ApiA11oyV1GenomeRoute
  '/api/a11oy/v1/honest': typeof ApiA11oyV1HonestRoute
  '/api/a11oy/v1/ledger': typeof ApiA11oyV1LedgerRoute
  '/api/a11oy/v1/organs': typeof ApiA11oyV1OrgansRouteWithChildren
  '/api/a11oy/v1/organs/history': typeof ApiA11oyV1OrgansHistoryRoute
  '/api/a11oy/v1/organs/$id': typeof ApiA11oyV1OrgansIdRoute
  '/api/a11oy/v1/spaces': typeof ApiA11oyV1SpacesRouteWithChildren
  '/api/a11oy/v1/spaces/health': typeof ApiA11oyV1SpacesHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/readyz': typeof ReadyzRoute
  '/_shell/admission': typeof ShellAdmissionRoute
  '/_shell/company': typeof ShellCompanyRoute
  '/_shell/console': typeof ShellConsoleRouteWithChildren
  '/_shell/estate': typeof ShellEstateRoute
  '/_shell/evidence': typeof ShellEvidenceRoute
  '/_shell/frontier': typeof ShellFrontierRoute
  '/_shell/investor': typeof ShellInvestorRoute
  '/_shell/killinchu': typeof ShellKillinchuRoute
  '/_shell/research': typeof ShellResearchRoute
  '/_shell/spaces': typeof ShellSpacesRoute
  '/_shell/trust': typeof ShellTrustRoute
  '/_shell/verify': typeof ShellVerifyRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/console/observability': typeof ShellConsoleObservabilityRoute
  '/_shell/verticals/$id': typeof ShellVerticalsIdRoute
  '/api/a11oy/tab-matrix': typeof ApiA11oyTabMatrixRoute
  '/api/a11oy/v1/admission': typeof ApiA11oyV1AdmissionRoute
  '/api/a11oy/v1/frontier': typeof ApiA11oyV1FrontierRoute
  '/api/a11oy/v1/genome': typeof ApiA11oyV1GenomeRoute
  '/api/a11oy/v1/honest': typeof ApiA11oyV1HonestRoute
  '/api/a11oy/v1/ledger': typeof ApiA11oyV1LedgerRoute
  '/api/a11oy/v1/organs': typeof ApiA11oyV1OrgansRouteWithChildren
  '/api/a11oy/v1/organs/history': typeof ApiA11oyV1OrgansHistoryRoute
  '/api/a11oy/v1/organs/$id': typeof ApiA11oyV1OrgansIdRoute
  '/api/a11oy/v1/spaces': typeof ApiA11oyV1SpacesRouteWithChildren
  '/api/a11oy/v1/spaces/health': typeof ApiA11oyV1SpacesHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/readyz'
    | '/admission'
    | '/company'
    | '/console'
    | '/estate'
    | '/evidence'
    | '/frontier'
    | '/investor'
    | '/killinchu'
    | '/research'
    | '/spaces'
    | '/trust'
    | '/verify'
    | '/console/observability'
    | '/verticals/$id'
    | '/api/a11oy/tab-matrix'
    | '/api/a11oy/v1/admission'
    | '/api/a11oy/v1/frontier'
    | '/api/a11oy/v1/genome'
    | '/api/a11oy/v1/honest'
    | '/api/a11oy/v1/ledger'
    | '/api/a11oy/v1/organs'
    | '/api/a11oy/v1/organs/history'
    | '/api/a11oy/v1/organs/$id'
    | '/api/a11oy/v1/spaces'
    | '/api/a11oy/v1/spaces/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/healthz'
    | '/readyz'
    | '/admission'
    | '/company'
    | '/console'
    | '/estate'
    | '/evidence'
    | '/frontier'
    | '/investor'
    | '/killinchu'
    | '/research'
    | '/spaces'
    | '/trust'
    | '/verify'
    | '/'
    | '/console/observability'
    | '/verticals/$id'
    | '/api/a11oy/tab-matrix'
    | '/api/a11oy/v1/admission'
    | '/api/a11oy/v1/frontier'
    | '/api/a11oy/v1/genome'
    | '/api/a11oy/v1/honest'
    | '/api/a11oy/v1/ledger'
    | '/api/a11oy/v1/organs'
    | '/api/a11oy/v1/organs/history'
    | '/api/a11oy/v1/organs/$id'
    | '/api/a11oy/v1/spaces'
    | '/api/a11oy/v1/spaces/health'
  id:
    | '__root__'
    | '/_shell'
    | '/healthz'
    | '/readyz'
    | '/_shell/admission'
    | '/_shell/company'
    | '/_shell/console'
    | '/_shell/estate'
    | '/_shell/evidence'
    | '/_shell/frontier'
    | '/_shell/investor'
    | '/_shell/killinchu'
    | '/_shell/research'
    | '/_shell/spaces'
    | '/_shell/trust'
    | '/_shell/verify'
    | '/_shell/'
    | '/_shell/console/observability'
    | '/_shell/verticals/$id'
    | '/api/a11oy/tab-matrix'
    | '/api/a11oy/v1/admission'
    | '/api/a11oy/v1/frontier'
    | '/api/a11oy/v1/genome'
    | '/api/a11oy/v1/honest'
    | '/api/a11oy/v1/ledger'
    | '/api/a11oy/v1/organs'
    | '/api/a11oy/v1/organs/history'
    | '/api/a11oy/v1/organs/$id'
    | '/api/a11oy/v1/spaces'
    | '/api/a11oy/v1/spaces/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  ReadyzRoute: typeof ReadyzRoute
  ApiA11oyTabMatrixRoute: typeof ApiA11oyTabMatrixRoute
  ApiA11oyV1AdmissionRoute: typeof ApiA11oyV1AdmissionRoute
  ApiA11oyV1FrontierRoute: typeof ApiA11oyV1FrontierRoute
  ApiA11oyV1GenomeRoute: typeof ApiA11oyV1GenomeRoute
  ApiA11oyV1HonestRoute: typeof ApiA11oyV1HonestRoute
  ApiA11oyV1LedgerRoute: typeof ApiA11oyV1LedgerRoute
  ApiA11oyV1OrgansRoute: typeof ApiA11oyV1OrgansRouteWithChildren
  ApiA11oyV1SpacesRoute: typeof ApiA11oyV1SpacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admission': {
      id: '/_shell/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof ShellAdmissionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/company': {
      id: '/_shell/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof ShellCompanyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/console': {
      id: '/_shell/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ShellConsoleRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/estate': {
      id: '/_shell/estate'
      path: '/estate'
      fullPath: '/estate'
      preLoaderRoute: typeof ShellEstateRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/evidence': {
      id: '/_shell/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof ShellEvidenceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/frontier': {
      id: '/_shell/frontier'
      path: '/frontier'
      fullPath: '/frontier'
      preLoaderRoute: typeof ShellFrontierRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/investor': {
      id: '/_shell/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof ShellInvestorRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/killinchu': {
      id: '/_shell/killinchu'
      path: '/killinchu'
      fullPath: '/killinchu'
      preLoaderRoute: typeof ShellKillinchuRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/research': {
      id: '/_shell/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ShellResearchRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/spaces': {
      id: '/_shell/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof ShellSpacesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/trust': {
      id: '/_shell/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof ShellTrustRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/verify': {
      id: '/_shell/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof ShellVerifyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/console/observability': {
      id: '/_shell/console/observability'
      path: '/observability'
      fullPath: '/console/observability'
      preLoaderRoute: typeof ShellConsoleObservabilityRouteImport
      parentRoute: typeof ShellConsoleRoute
    }
    '/_shell/verticals/$id': {
      id: '/_shell/verticals/$id'
      path: '/verticals/$id'
      fullPath: '/verticals/$id'
      preLoaderRoute: typeof ShellVerticalsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/a11oy/tab-matrix': {
      id: '/api/a11oy/tab-matrix'
      path: '/api/a11oy/tab-matrix'
      fullPath: '/api/a11oy/tab-matrix'
      preLoaderRoute: typeof ApiA11oyTabMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a11oy/v1/admission': {
      id: '/api/a11oy/v1/admission'
      path: '/api/a11oy/v1/admission'
      fullPath: '/api/a11oy/v1/admission'
      preLoaderRoute: typeof ApiA11oyV1AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a11oy/v1/frontier': {
      id: '/api/a11oy/v1/frontier'
      path: '/api/a11oy/v1/frontier'
      fullPath: '/api/a11oy/v1/frontier'
      preLoaderRoute: typeof ApiA11oyV1FrontierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a11oy/v1/genome': {
      id: '/api/a11oy/v1/genome'
      path: '/api/a11oy/v1/genome'
      fullPath: '/api/a11oy/v1/genome'
      preLoaderRoute: typeof ApiA11oyV1GenomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a11oy/v1/honest': {
      id: '/api/a11oy/v1/honest'
      path: '/api/a11oy/v1/honest'
      fullPath: '/api/a11oy/v1/honest'
      preLoaderRoute: typeof ApiA11oyV1HonestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a11oy/v1/ledger': {
      id: '/api/a11oy/v1/ledger'
      path: '/api/a11oy/v1/ledger'
      fullPath: '/api/a11oy/v1/ledger'
      preLoaderRoute: typeof ApiA11oyV1LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a11oy/v1/organs': {
      id: '/api/a11oy/v1/organs'
      path: '/api/a11oy/v1/organs'
      fullPath: '/api/a11oy/v1/organs'
      preLoaderRoute: typeof ApiA11oyV1OrgansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a11oy/v1/organs/history': {
      id: '/api/a11oy/v1/organs/history'
      path: '/history'
      fullPath: '/api/a11oy/v1/organs/history'
      preLoaderRoute: typeof ApiA11oyV1OrgansHistoryRouteImport
      parentRoute: typeof ApiA11oyV1OrgansRoute
    }
    '/api/a11oy/v1/organs/$id': {
      id: '/api/a11oy/v1/organs/$id'
      path: '/$id'
      fullPath: '/api/a11oy/v1/organs/$id'
      preLoaderRoute: typeof ApiA11oyV1OrgansIdRouteImport
      parentRoute: typeof ApiA11oyV1OrgansRoute
    }
    '/api/a11oy/v1/spaces': {
      id: '/api/a11oy/v1/spaces'
      path: '/api/a11oy/v1/spaces'
      fullPath: '/api/a11oy/v1/spaces'
      preLoaderRoute: typeof ApiA11oyV1SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a11oy/v1/spaces/health': {
      id: '/api/a11oy/v1/spaces/health'
      path: '/health'
      fullPath: '/api/a11oy/v1/spaces/health'
      preLoaderRoute: typeof ApiA11oyV1SpacesHealthRouteImport
      parentRoute: typeof ApiA11oyV1SpacesRoute
    }
  }
}

interface ShellConsoleRouteChildren {
  ShellConsoleObservabilityRoute: typeof ShellConsoleObservabilityRoute
}

const ShellConsoleRouteChildren: ShellConsoleRouteChildren = {
  ShellConsoleObservabilityRoute: ShellConsoleObservabilityRoute,
}

const ShellConsoleRouteWithChildren = ShellConsoleRoute._addFileChildren(
  ShellConsoleRouteChildren,
)

interface ShellRouteChildren {
  ShellAdmissionRoute: typeof ShellAdmissionRoute
  ShellCompanyRoute: typeof ShellCompanyRoute
  ShellConsoleRoute: typeof ShellConsoleRouteWithChildren
  ShellEstateRoute: typeof ShellEstateRoute
  ShellEvidenceRoute: typeof ShellEvidenceRoute
  ShellFrontierRoute: typeof ShellFrontierRoute
  ShellInvestorRoute: typeof ShellInvestorRoute
  ShellKillinchuRoute: typeof ShellKillinchuRoute
  ShellResearchRoute: typeof ShellResearchRoute
  ShellSpacesRoute: typeof ShellSpacesRoute
  ShellTrustRoute: typeof ShellTrustRoute
  ShellVerifyRoute: typeof ShellVerifyRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellVerticalsIdRoute: typeof ShellVerticalsIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAdmissionRoute: ShellAdmissionRoute,
  ShellCompanyRoute: ShellCompanyRoute,
  ShellConsoleRoute: ShellConsoleRouteWithChildren,
  ShellEstateRoute: ShellEstateRoute,
  ShellEvidenceRoute: ShellEvidenceRoute,
  ShellFrontierRoute: ShellFrontierRoute,
  ShellInvestorRoute: ShellInvestorRoute,
  ShellKillinchuRoute: ShellKillinchuRoute,
  ShellResearchRoute: ShellResearchRoute,
  ShellSpacesRoute: ShellSpacesRoute,
  ShellTrustRoute: ShellTrustRoute,
  ShellVerifyRoute: ShellVerifyRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellVerticalsIdRoute: ShellVerticalsIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface ApiA11oyV1SpacesRouteChildren {
  ApiA11oyV1SpacesHealthRoute: typeof ApiA11oyV1SpacesHealthRoute
}

const ApiA11oyV1SpacesRouteChildren: ApiA11oyV1SpacesRouteChildren = {
  ApiA11oyV1SpacesHealthRoute: ApiA11oyV1SpacesHealthRoute,
}

const ApiA11oyV1SpacesRouteWithChildren =
  ApiA11oyV1SpacesRoute._addFileChildren(ApiA11oyV1SpacesRouteChildren)

interface ApiA11oyV1OrgansRouteChildren {
  ApiA11oyV1OrgansHistoryRoute: typeof ApiA11oyV1OrgansHistoryRoute
  ApiA11oyV1OrgansIdRoute: typeof ApiA11oyV1OrgansIdRoute
}

const ApiA11oyV1OrgansRouteChildren: ApiA11oyV1OrgansRouteChildren = {
  ApiA11oyV1OrgansHistoryRoute: ApiA11oyV1OrgansHistoryRoute,
  ApiA11oyV1OrgansIdRoute: ApiA11oyV1OrgansIdRoute,
}

const ApiA11oyV1OrgansRouteWithChildren =
  ApiA11oyV1OrgansRoute._addFileChildren(ApiA11oyV1OrgansRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  HealthzRoute: HealthzRoute,
  ReadyzRoute: ReadyzRoute,
  ApiA11oyTabMatrixRoute: ApiA11oyTabMatrixRoute,
  ApiA11oyV1AdmissionRoute: ApiA11oyV1AdmissionRoute,
  ApiA11oyV1FrontierRoute: ApiA11oyV1FrontierRoute,
  ApiA11oyV1GenomeRoute: ApiA11oyV1GenomeRoute,
  ApiA11oyV1HonestRoute: ApiA11oyV1HonestRoute,
  ApiA11oyV1LedgerRoute: ApiA11oyV1LedgerRoute,
  ApiA11oyV1OrgansRoute: ApiA11oyV1OrgansRouteWithChildren,
  ApiA11oyV1SpacesRoute: ApiA11oyV1SpacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
